config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts do
    resources :comments
  end
  get '/signin', to: 'users#signin_prompt'
  post '/signin', to: 'users#signin'
  get '/signout', to: 'users#signout'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # index
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.all
  end

  # new
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  # create
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  #show
  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  # edit
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  # update
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)

    redirect_to post_path( @post )
  end

  # destroy
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_path( @post )
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :text, :created_at, :updated_at, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # index
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params)
    redirect_to posts_path(@post)
  end

  # edit
  def edit
    @post = Post.find(params[:id])
  end

  # update
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  # destroy
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path()
  end

  private
  def post_params
    params.require(:post).permit(:title, :author, :text, :created_at, :updated_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def sign_up
  end

  def sign_up!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_up
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.username}!"
      cookies[:username] = {
        value: @user.username,
        expires: 100.years.from_now
      }
      session[:user] = @user
    end
    flash[:notice] = message
    redirect_to action: :sign_in
  end

  def sign_out
    flash[:notice] = "You're signed out!"
    reset_session
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :text %>
  <%= f.text_field :text %>

  <%= f.submit %>
<% end %>

<%= form_for [@post, @comment], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/comments/index.html.erb
<h2>Comments <%= link_to "(+)", new_post_comment_path %></h2>

<table>
  <% @comments.each do |comment| %>
  <tr>
    <td><h4><%= comment.text %></td></h4>
  </tr>
  <tr>
    <td><h4>By:<%= comment.author %></td></h4>
  </tr>
  <tr>
    <td><h4>About:<%= comment.post.title %></td></h4>
  </tr>
  <tr>
    <td><%= link_to "view", post_comment_path( @post, comment )%></td>
  </tr>
  <% end %>
</table>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :text %>
  <%= f.text_field :text %>

  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h2><%= @comment.text %> <%= link_to "(edit)", edit_post_comment_path(@post, @comment) %></h2>
<h3>About: <%= @comment.post.title %></h3>
<h3>By:<%= @comment.author %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav>
    <ul class="menu">
      <li><a href="/signin">Sign in</a></li>
      <li><%= link_to 'New post', new_post_path %></li>
    </ul>
  </nav>
  <header>
    <%= image_tag("scribble.jpg", size: "200x166") %>
  </header>
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :text %>
  <%= f.text_field :text %>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

<%= form_for @post, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<ul class="postList">
  <% @posts.each do |post| %>
    <li><h3><%= post.title %></h3></li>
    <%= post.author %>
    <%= link_to 'view', post %>

  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %>
  <%= link_to "(edit)", edit_post_path(@post) %>
</h2>
<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>
<p>
  <%= @post.text %>
</p>

<h3>Comments <%= link_to "(new)", new_post_comment_path(@post) %></h3>
<table>
  <% @post.comments.each do |comment| %>
    <tr>
      <td><%= comment.text %></td>
    </tr>
    <tr>
      <td><p><%= comment.author %></p>
        <p><%= link_to "(edit)", edit_post_comment_path(@post, comment) %></p>
        </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', posts_path %>

app/views/users/signin_prompt.html.erb
<%= form_tag("/signin", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>